### ISSUE TITLE
Create a projection for Cartography Filter

### ISSUE THREAD

**Issue by gon-nexus** [sitmun/sitmun-backend-core#105]
We need the id of territorial level in the projection view of Filter (Cartography screen - Filter table)

![image](https://user-images.githubusercontent.com/73172087/118796166-a30e5800-b89b-11eb-9a47-93bb6edbf5b3.png)

Thanks!

**Comment by fjlopez** [comment]
Created projection `view` for cartography filter

| property | JSON type | mandatory | 
| -- | -- | :--: | 
| `id` | `integer` | yes | 
| `name` | `string` | yes |
| `required`| `boolean` | yes | 
| `type`| `string` | yes | 
| `territorialLevelId`| `integer` | no | 
| `territorialLevelName`| `string` | no | 
| `column`| `string` | no | 
| `values`| `array` of `string` | no | 
| `valueType`| `string` | no |

**Comment by gon-nexus** [comment]
Yes! It works as expected!
