### ISSUE TITLE
Add center and zoom to Territory

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-backend-core#115]
After reviewing https://github.com/sitmun/sitmun-admin-app/issues/43 a territory needs:

- [x] center (defaults to the centroid of the extent)
- [x] default zoom level (optional)

**Comment by fjlopez** [comment]
Created properties
- `defaultZoomLevel`: integer
- `center`: object with `x` number and `y` number

**Comment by gon-nexus** [comment]
When you save a territory with defaultZoomLevel or center, the request returns the territory with that fields, but if you make the get request again, it has not these fields.

**Comment by fjlopez** [comment]
I missed to add them to the projection view. I will fix it today.

**Comment by fjlopez** [comment]
@fjlopez fixed!
