### ISSUE TITLE
New projection on Territory

### ISSUE THREAD

**Issue by gon-nexus** [sitmun/sitmun-backend-core#118]
We need the projection of type id on Territory response.

Thanks!

**Comment by fjlopez** [comment]
Added:

-  `typeId`
-  `typeName`

In addition, `groupTypeName`, `groupTypeId` and `scope` are marked as deprecated properties and will be removed in a future version.  Replace ASAP by `typeId` and `typeName`.

**Comment by fjlopez** [comment]
Done @gon-nexus

**Comment by gon-nexus** [comment]
Ok! The two projections are correct, but due to a new issue we will also need two new projections: topType and bottomType

Thanks!

**Comment by fjlopez** [comment]
In order to be consistent with the naming of other properties, the name of the two new properties are:
- `typeTopType`
- `typeBottomType`
