### ISSUE TITLE
Split CartographyParameters in two lists in Cartography

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-backend-core#122]
Cartography parameters in a Cartography are used as parameters for:

- the portrayal service (identified by `service`)
- the spatial selection service (identified by `spatialSelectionService`) 

| cartography parameter type | `service` | `spatialSelectionService` | Note | 
| --- | --- | --- | --- |
| EDIT | ✖️  |  ✔️
| ~~FILTRO~~  | ✖️ | ✖️ | Deprecated
| FILTRO_ESPACIAL | ✖️ |  ✔️ | Marker?
| FILTRO_INFO | ✔️ | ✖️ | Marker?
| INFO |  ✔️ | ✖️
| ~~INFOSELECT~~  | ✖️ | ✖️ | Deprecated
| SELECT | ✖️ | ✔️ | 

@lucenasj fill the above table and confirm
- [ ] all the SITMUN2 cartography parameter types are included
- [ ] all the known uses in SITMUN2 for each parameter are confirmed

It is ok that a cartography parameter type is present in different service types. 

The cartography parameter table will be split in at least two tables. The first will keep the current name. The new table will contain the parameters for the `spatialSelectionService`.

The code list `cartographyParameter.type` will be spilt in at least two code lists. The first will keep the current name. The new table will contain the code list for the types of the parameters for the `spatialSelectionService`.

**Comment by gon-nexus** [comment]
-Parameter type "INFO" is used in the "Parameter configuration" layers table, as we only display the parameters with this type, and when creating a new parameter,we force it to have this type.

- Parameter type "INFO_SELECT" the same but with the "Spatial Selection" table, only parameters with this type are displayed, , and when creating a new spatial selection parameter we force it to have this type.

- Parameter type "FILTRO_INFO" if the "applyFilterToGetFeatureInfo" element in cartography is null, we check if there is a parameter with this type, once the cartography has applyFilterToGetFeatureInfo assigned to true or false this call is not done.

- Parameter type "FILTRO_ESPACIAL" if the "applyFilterToSpatialSelection" element in cartography is null, we check if there is a parameter with this type, once the cartography has applyFilterToSpatialSelection assigned to true or false this call is not done.

**Comment by fjlopez** [comment]
@lucenasj @gon-nexus please, confirm:

- "Parameter configuration" parameters: "INFO" (in Sitmun 2, tab Configuració paràmeters), "FILTRO_INFO" (in Sitmun 2, tab Dades de la cartografía, filtrar per municipi a la info)
- "Spatial selection" parameters: "INFOSELECT" (in Sitmun 2, parameters from the tab Selecció espacial), "FILTRO_ESPACIAL" (in Sitmun 2, tab Dades de la cartografía, filtrar per municipi a la selecció espacial)   
- Which are the purpose of "SELECT", "FILTRO", and "EDIT" parameters (check Sitmun 2 codebase, they are used)?

In addition, don't hardcode behaviour related to codelists. As these values may change from a partner to another for various reasons these values MUST be provided by the backend in the ConfigurationParameters API. That is:
- the default type for new parameters in "parameter configuration" (in this case "INFO")
- the default type for new parameters in "spatial selection" (in this case "INFOSELECT")
- the type or types to check when applyFilterToGetFeatureInfo is set (in this case "FILTRO_INFO")
- the type or types to check when applyFilterToSpatialSelection is set (in this case "FILTRO_ESPACIAL")

Note: INFO_SELECT should be a typo. The correct value is INFOSELECT.

**Comment by gon-nexus** [comment]
- First of all, I've been wrong with the type we force in creating a spatial selection parameter, it's "EDIT" not "INFOSELECT", INFO SELECT is deprecated and we don't use it, we haven't seen uses in sitmun2.
- SELECT parameter is used by the checkbox above the Spatial Configuration Parameter table (selectable)
- The "FILTER" parameter was used in a checkbox that no longer exists, so it is deprecated (in sitmun2 is the checkbox for filter info by municipality)

**Comment by fjlopez** [comment]
I have updated the description of the issue with your comments. Could you confirm it? 

I wonder about SELECT,  there is a property `selectableFeatureEnabled` in Cartography that was also present in sitmun 2 (`CAR_SELECTABL`). Having the parameter `SELECT` seems to be equivalent to set `selectableFeatureEnabled` to `true`. If so, why it is necessary?

**Comment by fjlopez** [comment]
@gon-nexus @lucenasj , the above table, is it OK? I need your answer to continue.

**Comment by fjlopez** [comment]
Pushed updates:
- created the relation `spatialSelectionParameters` in `Cartography` of type `CartographySpatialSelectionParameter`
- `CartographySpatialSelectionParameter` has the same structure as `CartographyParameter` and it is available at `/api/cartography-spatial-selection-parameters`.
- `CartographyParameters` should be used for the parameters in the panel `Parameter configuration`
- `CartographySpatialSelectionParameter` should be used for the parameters in the panel `Spatial selection`
- Type code list of `CartographyParameters` only contains values INFO and FILTRO_INFO
- `CartographySpatialSelectionParameter` has their own code lists (`cartographySpatialSelectionParameter.format` and `cartographySpatialSelectionParameter.type`); `type` code list only contains values EDIT, FILTRO_ESPACIAL and SELECT
- Code list values have a new property: `defaultCode`. This avoid to hardcode a value in admin code. INFO and EDIT have `defaultCode` value set `true`.  

Regarding to:
> Parameter type "FILTRO_INFO" if the "applyFilterToGetFeatureInfo" element in cartography is null, we check if there is a parameter with this type, once the cartography has applyFilterToGetFeatureInfo assigned to true or false this call is not done.
> Parameter type "FILTRO_ESPACIAL" if the "applyFilterToSpatialSelection" element in cartography is null, we check if there is a parameter with this type, once the cartography has applyFilterToSpatialSelection assigned to true or false this call is not done.

Why these "parameters" are needed? If in the data migration from SITMUN 2 to SITMUN 3 we replace "FILTRO_INFO"  by applyFilterToGetFeatureInfo=true and FILTRO_ESPACIAL by applyFilterToSpatialSelection=true, keep these parameter types would be unnecessary, isn't?

**Comment by gon-nexus** [comment]
Everything is correct, but I have a doubt, in the codelist of type spatial selection, the value 'EDIT' has as its description 'Date', is it correct? I say this because I have seen that everyone else has similar names between value and description, but this codelist does not.

Regarding to: 

> Why these "parameters" are needed? If in the data migration from SITMUN 2 to SITMUN 3 we replace "FILTRO_INFO" by applyFilterToGetFeatureInfo=true and FILTRO_ESPACIAL by applyFilterToSpatialSelection=true, keep these parameter types would be unnecessary, isn't?

We also believe it, so we have decided to stop reviewing the parameters if the field is null!

Thanks!

**Comment by fjlopez** [comment]
> Everything is correct, but I have a doubt, in the codelist of type spatial selection, the value 'EDIT' has as its description 'Date', is it correct? I say this because I have seen that everyone else has similar names between value and description, but this codelist does not

@gon-nexus Can you share (add a link to the code) the request (TypeScript code) that give you access to such description?  `EDIT` has as description `EDIT` because the consortium members didn't know its meaning. But in the entity pCartographySpatialSelectionParameter` (and `CartographyParameter`) there are two properties with code lists:

- `type`:  `cartographySpatialSelectionParameter.type`
- `format`: `cartographySpatialSelectionParameter.format`

This is relevant because the first member of the code list related to `format` is `F` with description `Date`.  I wonder if you are mixing requests or responses. Could you check it?

> We also believe it, so we have decided to stop reviewing the parameters if the field is null!

So, FILTRO_INFO and FILTRO_ESPACIAL rows in codelists and parameters can be deleted if the corresponding applyFilterToGetFeatureInfo and applyFilterToSpatialSelection properties are set to true, isn't? Confirm me and I will update the test data.

**Comment by gon-nexus** [comment]
I'm taking a picture of HAL because I think it's gonna be clearer:

![image](https://user-images.githubusercontent.com/73172087/127441039-3e5023c9-7a11-4325-858b-07a3c33a4b20.png)


As you can see, the value of the value field is "EDIT" but the description is "Data", and as the codeListName field indicates, the codelist is cartographySpatialSelectionParameter.type.


> So, FILTRO_INFO and FILTRO_ESPACIAL rows in codelists and parameters can be deleted if the corresponding applyFilterToGetFeatureInfo and applyFilterToSpatialSelection properties are set to true, isn't? Confirm me and I will update the test data.

Yes!!

**Comment by fjlopez** [comment]
> As you can see, the value of the value field is "EDIT" but the description is "Data", and as the codeListName field indicates, the codelist is cartographySpatialSelectionParameter.type.

This is a bug in the backend as the the "description" value should be "EDIT". I'll will fix this ASAP.

**Comment by fjlopez** [comment]
@gon-nexus Fixed

**Comment by fjlopez** [comment]
> So, FILTRO_INFO and FILTRO_ESPACIAL rows in codelists and parameters can be deleted if the corresponding applyFilterToGetFeatureInfo and applyFilterToSpatialSelection properties are set to true, isn't? Confirm me and I will update the test data.

@gon-nexus Applied.
