### ISSUE TITLE
New projection on permissions of a Layer

### ISSUE THREAD

**Issue by gon-nexus** [sitmun/sitmun-backend-core#124]
We need a projection of the roles name of the permissions of a layer, as a permission can have more than one role, we could put them inside an array.

Example of the link where we need the projection:  http://localhost:8080/api/cartographies/1256/permissions

Thanks!!

**Comment by fjlopez** [comment]
@gon-nexus Cartography Permissions has no projection yet. In addition to such property (e.g. `roleNames`), which other properties must be available in the projection.

**Comment by gon-nexus** [comment]
We only need roleNames! Thanks!

**Comment by fjlopez** [comment]
The closer solution to your request will return the following structure:

```json
"_embedded" : {
   "cartography-groups" : [ {
      "id": identifier_of_the_cartography_group,
      "name": name_of_the_cartography_group
      "roleNames: [ "role_name_1", "role_name_2", ... ]
    }]
}
```
I have added `id` because permissions may return a list. 

@gon-nexus do you agree with this structure?

**Comment by gon-nexus** [comment]
Yes, that structure is correct!

**Comment by fjlopez** [comment]
@gon-nexus done
