### ISSUE TITLE
Applications link in a background

### ISSUE THREAD

**Issue by gon-nexus** [sitmun/sitmun-backend-core#125]
As requested here: https://github.com/sitmun/sitmun-admin-app/issues/98

In a basemap (background), we need the url (like a link) of applications that use this basemap (in application, we have the link to the background used).

**Comment by fjlopez** [comment]
You have already such information if from a `Background` when you retrieve its `backgrounds` which returns the set of `ApplicationBackgrounds` that contains the link to the application and the position in the collection of backgrounds of such application. 

The name of the property `backgrounds` is not adequate and we should change it to `applications`. Do you agree?

**Comment by gon-nexus** [comment]
I agree with the rename!

**Comment by gon-nexus** [comment]
Also we will need the projection of applicationName! Thanks!

**Comment by fjlopez** [comment]
Your request is unclear. Do you need in the projection of Background something similar to:
```json
"applications": [ { "id": 3, "name": "App 1"},  { "id": 5, "name": "App 2"}]
```
where `id` is `Application.id`, and `name` is `Application.name`?

**Comment by gon-nexus** [comment]
No, we need something like:
ApplicationBackgrounds: {"id": 3, "applicationName": "App 1"}

The projection is from ApplicationBackgrounds, so there is only one application, now is returning the name of the background, but we also need the application's name

**Comment by fjlopez** [comment]
Understood!

**Comment by fjlopez** [comment]
@gon-nexus done
