### ISSUE TITLE
New field on TreeNode

### ISSUE THREAD

**Issue by gon-nexus** [sitmun/sitmun-backend-core#126]
We need the TNO_STYLE field on treeNodes (STM_TREE_NOD)

**Comment by fjlopez** [comment]
@lucenasj @gon-nexus @codinachssm 

We need to agree first definition, some implementation details and read/write semantics. This is my proposal.

**Definition**

`style` in a tree node identifies the name of the style of a cartography to be used by the cartography associated to this tree node.  `TNO_STYLE` is it storage in the SQL model

**Implementation**

Given a TreeNode related to a Cartography with 0..N CartographyStyles:
- TreeNode has a String property named `style` backed by `TNO_STYLE`.
- `style` should be either empty or equal to the `name` of one of the CartographyStyles of the Cartography

**Read semantics**
- The administrator app, after retrieving a TreeNode from the API, must produce a warning when the TreeNode:
   -  has a Cartography, 
   - `style` is not empty, and
   - `style` is not equal to the `name` of one of the CartographyStyles of the Cartography. 

**Write semantics**
- Saving a TreeNode may fail in the administrator app and the backend when:
   -  it has a Cartography, and
   - `style` is not empty, and 
   - `style` is not equal to the `name` of one of the CartographyStyles of the Cartography. 
- Saving a TreeNode may fail  in the administrator app and the backend when:
   -  the node not has a Cartography, and 
   - `style` is not empty

**Comment by fjlopez** [comment]
@lucenasj @gon-nexus @codinachssm

**Additional considerations**

* The backend should do additional checks in order to ensure consistency:
  - If a CartographyStyle is referenced by a `TreeNode`, the CartographyStyle can't be deleted.
  - If the name of a CartographyStyle is renamed, all the `TreeNode` that reference such style must update its `style` property to the new name.

**Comment by IDEmenorca** [comment]
I Agree

**Comment by gon-nexus** [comment]
When I save a treeNode with style it is saved correctly, but when I do a get request of the same treeNode , I don't get back the treeNode's style. @fjlopez 


HAR of the save request
[HAR_SAVE_NODE_WITH_STYLE.zip](https://github.com/sitmun/sitmun-backend-core/files/7511944/HAR_SAVE_NODE_WITH_STYLE.zip)
:

**Comment by fjlopez** [comment]
@gon-nexus It is impossible to detect the problem with a HAR file of 226334 lines. Please, reduce it to include only the PUT request and the GET request, and/or add the URI that you makes for the PUT or the GET

**Comment by gon-nexus** [comment]
For example i make a put to: http://localhost:8080/api/tree-nodes/8455

With the field style like this:
![image](https://user-images.githubusercontent.com/73172087/141136774-8bfa3947-0d1a-4c85-8fcc-e2f3b93e851b.png)

The cartography was 1087, which I had created a style with the name "Prova" (I also tried with the cartography that you put an example of style, but it doesn't work either).

The request returns status 200 (OK), and the request answer includes the style:

![image](https://user-images.githubusercontent.com/73172087/141138110-233902c9-e723-4c4b-9dd6-9d5564bdbe38.png)

But when i do the get request for the tree, this node (8455), it has not the style field:

![image](https://user-images.githubusercontent.com/73172087/141138578-93891e4e-3d69-4af3-abd7-1b711c3b9f72.png)

**Comment by fjlopez** [comment]
@gon-nexus Is the last a projection request?

**Comment by gon-nexus** [comment]
Yes, it's a projection request

**Comment by fjlopez** [comment]
The property was not in the projection. It should work now.
