### ISSUE TITLE
Add style names to the projection of the cartography 

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-backend-core#127]
The `Cartography` projection should expose a list of available styles (e.g. `stylesNames: ["style1", "style2", ...]`). Related to #126.

**Comment by gon-nexus** [comment]
Will it also be possible to add to Tree-Node projection? As we do with the cartographyName and the cartographyId. @fjlopez

**Comment by fjlopez** [comment]
@gon-nexus Something like:
```json
{ "styles": [{"id": 1, "name":"style1"}, {"id":523, "name":"style2"}, ...] }
```

instead of `styleNames`?

**Comment by fjlopez** [comment]
@gon-nexus So, the request is not about adding it to `Cartography` but adding it to `TreeNode`? Can you confirm.

**Comment by gon-nexus** [comment]
We need the two projections, the one now in cartography (which is correct), and the new one in TreeNode, thanks!

**Comment by fjlopez** [comment]
This morning I reviewed this request (`cartographyStylesNames` in `TreeNode`) and it does not work in the current version of Spring. 😞

**Comment by gon-nexus** [comment]
Don't worry! I found a way to do this without the projection, thank you very much!
