### ISSUE TITLE
Initial Extent moved to application

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-backend-core#158]
**Is your feature request related to a problem? Please describe.**

In `/api/config/client/profile/` response the `initialExtension` must not be a `territory` property. Other `territory` properties such as `center` and `defaultZoomLevel` have not sense. Hence the property `territory` has no sense in this moment.

**Describe the solution you'd like**

- `territory` must be removed.
- `application.initialExtent` is added (it may contain an extension adapted to the needs of the application).

**Comment by srodriguez7** [comment]
Checked and added to viewer
