### ISSUE TITLE
Endpoint to list available SITMUN applications by territory

### ISSUE THREAD

**Issue by srodriguez7** [sitmun/sitmun-backend-core#161]
**Is your feature request related to a problem? Please describe.**
Currently, clients do not have an efficient way to know which SITMUN applications are available for the user, given a territory. The user can either be identified by a bearer token or can be a public user. 

**Describe the solution you'd like**
An endpoint (`/api/config/client/{terrId}/applications`) that returns the list of available SITMUN applications for the user, given a territory. This endpoint should be able to handle both public and authenticated users, and provide the list of applications.

**Comment by fjlopez** [comment]
The endpoint must be `/api/config/client/territory/{terrId}/applications` for consistence
