### ISSUE TITLE
Tree nested levels are not set properly

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-backend-core#169]
**Describe the bug**
Tree nested levels are not set properly when more than 2 levels are needed. If a tree has morae than 2 levels, then all of them are rendered in a 2 levels structure

**To Reproduce**
1. Go to the administrator, and edit tree number 33. As you can see, there are two different level from root. First one (Capas), contains "pnoa" layer, and other two nodes (gruopo1 and grupo2). Each of these nodes contain more layers.

![err11](https://github.com/sitmun/sitmun-backend-core/assets/6534787/e74dffb8-cb5e-4b4c-a857-0b079d164818)
..'

4. Open viewer and see how tree is rendered. All nodes are displayed at the same level
![image](https://github.com/sitmun/sitmun-backend-core/assets/6534787/3b08785d-3049-47a8-95f2-bdfddc6bcd64)

**Expected behavior**
The same structure at the Administrator module should be displayed at viewer module

**Comment by fjlopez** [comment]
Data send from the backend is OK. The bug is on the client side. Given the excerpt below from https://sitmun-backend-core.herokuapp.com/api/config/client/profile/12/4 
```jsonc
"trees" : [ {
    "id" : "tree/33",
    "title" : "arbol test",
    "image" : null,
    "rootNode" : "node/8507",
    "nodes" : {
      "node/8509" : { 
        "title" : "Grupo 1",
        "resource" : null,
        "isRadio" : null,
        "children" : [ "node/8511", "node/8513" ]
      },
      "node/8508" : { 
        "title" : "Grupo 2",
        "resource" : null,
        "isRadio" : null,
        "children" : [ "node/8512" ]
      },
      "node/8507" : {  
        "title" : "Capas",
        "resource" : null,
        "isRadio" : null,
        "children" : [ "node/8509", "node/8508", "node/8510" ]
      },
      "node/8512" : {
        "title" : "altimetria",
        "resource" : "layer/7",
        "isRadio" : null,
        "children" : null
      },
      "node/8511" : {  
        "title" : "limits",
        "resource" : "layer/4",
        "isRadio" : null,
        "children" : null
      },
      "node/8510" : {  // third node
        "title" : "pnoa",
        "resource" : "layer/3",
        "isRadio" : null,
        "children" : null
      },
      "node/8513" : {
        "title" : "Camís de cavalls",
        "resource" : "layer/1304",
        "isRadio" : null,
        "children" : null
      }
    }
  } ]
```

and assuming that the node "node/8507" must be hidden, the tree should have the following form:

- node/8509: Grupo 1
   - node/8511: limits
   - node/8513: Camís de cavalls
- node/8508: Grupo 2
   - node/8512:  altimetria
- node/8510: pnoa

**Comment by mvinent** [comment]
I agree that it's a bug on the client side. The LayerCatalogControl is not prepared to handle more than one level of virtual nodes (by virtual nodes, I understand nodes that do not originate from any capabilities).
I'll review the client code to resolve this issue.
