### ISSUE TITLE
Unify the data structure of the response json

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-backend-core#170]
**Describe the bug**
When declaring a new task without parameters the response json shows as follows **"parameters" : null**, but when adding a parameter and then deleting this same parameter the response json shows like this **"parameters" : { "parameters" : [ ] }**.

**To Reproduce**
1. Go to admin and create a new task or edit an existing task that does not have any parameter
2. Check how the task appears on the response json, it should appear like this 
'{
    "id" : "task/xx",
    "parameters" : null,
    "ui-control" : "xxxxxx"
  }'
4. Go to admin and add a parameter to the task we are testing
5. Go to admin and delete the parameters so the task does not have any parameter left
6. Check how the task appears on the response json, now appears like this 
'{
    "id" : "task/xx",
    "parameters" : {
      "parameters" : [ ]
    "ui-control" : "xxxxxx"
  }'

**Expected behavior**
We would expect the same structure for the json when the task does not have any parameter

**Screenshots**

**Comment by fjlopez** [comment]
This behavior is coherent with the definition of the **Basic Task**.

<img width="830" alt="image" src="https://github.com/sitmun/sitmun-backend-core/assets/3294927/82722f8f-9f11-470c-89e4-618048efae8a">

https://github.com/sitmun/sitmun-backend-core/issues/172#issuecomment-1663963106 proposes a potential solution to this issue that requires an agreement on the definition of a new **Task Type**.
