### ISSUE TITLE
Access to services with invalid or self-signed SSL certificate

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-backend-core#186]
**Describe the bug**
"When attempting to configure the Catastro and Costas web services in the SITMUN administrator, various errors and malfunctions occur, making the process impossible."

**To Reproduce**
1. Go to 'services'
2. Click on 'new'
3. Try to configure Catastro or Costas WMS 

- http://wms.mapama.es/sig/Costas/DPMT/wms.aspx
- https://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx

5. The ‘Obtener Datos’ button doesn’t work, and when trying to configure it manually, the layer does not appear in the layer tree of the viewer.

**Expected behavior**
It should be possible to configure those wms services

**Screenshots**
![imagen](https://github.com/user-attachments/assets/e11ca939-54ce-464d-b91e-d53b802b0279)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fjlopez** [comment]
@RicardCots fixed; validate updated behaviour. Note that the request to the mapama server must be https.
