### ISSUE TITLE
Size matters:  geo_abstract field is too small

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-backend-core#187]
**Describe the bug**
The geo_abstract field of the stm_geoinfo table only allows 250 characters which is clearly not enough. This fact also causes errors in layer registration when importing data from the service and layer descriptions are longer. 

Additionally, the geo_daturl and geo_legendurl fields are 4000 (varchar4000) characters long, which seems excessive, although it does not cause performance problems. 

**To Reproduce**
1. Go to a the layer editing form
2. Create an abstract bigger than 250 characters
3. Save and see error

**Expected behavior**
No size problems. 

**Screenshots**
![imagen](https://github.com/user-attachments/assets/8e27be15-c81f-4f37-ae5c-fbff8798d516)

**Comment by fjlopez** [comment]
Fixed, next fresh installs of SITMUN will have space for long abstracts (4000 characters.)
