### ISSUE TITLE
Unavailable layer or service

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-backend-core#22]
A **Layer** (i.e. *Cartographies*) may be deleted from a *Service* after an update. An automatic delete is a bad idea because lot of information may get lost. A deleted *Layer* must be marked as **blocked** when the *Service* capabilities is updated in the *SITMUN administrator*. *SITMUN applications* may use this information to hide or disable access to those *Layers* in user interfaces. 

An *admin user* of  SITMUN may detect an issue in the content of a **Layer** (e.g. wrong data). It may mark the *Layer* as **blocked** until the issue is fixed.

A **Service** may be down, temporarily or forever. This may cause problems to users. An *admin user* of SITMUN  should be able to mark a *Service* as **blocked** when it is down. If a *Service* is unavailable, *SITMUN applications* may use this information to hide or disable access to all the *Layers* of the unavailable *Service* in user interfaces.

An *admin user* must be able to add and remove the **blocked** mark in **Layers**  and **Services** at will.

**Comment by IDEmenorca** [comment]
A good feature would be the possibility of executing a batch process to all the services loaded in the SITMUN administrator to detect any type of unavailability, both in layers and in services.

**Comment by codinachssm** [comment]
Totally agree!
