### ISSUE TITLE
Add backgroundName and backgroundDesc to the projection "view" of application-background

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#54]
Applications-Backgrounds require an easy access to the name and description of backgrounds in the projection view.

**Comment by fjlopez** [comment]
This requires:
- [ ] Create a projection for `ApplicationBackground` named `view`.
- [ ] Create a property named `backgroundName` that contains the value of the `name` of the background.
- [ ] Create a property named `backgroundDescription` that contains the value of the `description` of the background.
