### ISSUE TITLE
Validate a connection api request

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#55]
The connection should be validated if it is a valid connection, making an API request to the backend

**Comment by lucenasj** [comment]
on response JSON object, is possible to change "cause" propertie to "message"?

**Comment by fjlopez** [comment]
In addition, a values of a potential connection can be tested with an authenticated POST at the endpoint `/api/connections/test`. 
- The request body is a JSON object with the properties `driver`, `url`, `user` and `password`.
- If the response has a http status of 401, the authentication has failed.
- If the response has a http status of 200, the connection is valid.
- If the response has a http status of 500, the connection is invalid valid. A JSON object is returned with two properties:
  - `error`: that can contains either `"Driver not found"` or `"SQL exception"`.
  - `message`: that contains a message providing additional information to the error.

**Comment by fjlopez** [comment]
@lucenasj, does the new endpoint solves the issue?

**Comment by lucenasj** [comment]
yes, issue solved
