### ISSUE TITLE
Add GroupTypeName and GroupTypeId to the projection "view" of territory

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#56]
Territory require an easy access to the ID and NAME of groupType in the projection view.

**Comment by fjlopez** [comment]
This requires:
- [ ] Create a projection for `Territory` named `view`.
- [ ] Create a property named `groupTypeId` that contains the value of the `id` of the group type or `null` if `groupType` is `null`.
- [ ] Create a property named `groupTypeName` that contains the value of the `name` of the group type or `null` if `groupType` is `null`
