### ISSUE TITLE
Add ServiceId, SpatialSelectServiceId and SpatialSelectServiceName to the projection "view" of cartography

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#58]
Cartography require an easy access to the ID of service, ID and Name of spatailSelectService in the projection view.

**Comment by fjlopez** [comment]
This requires:
- [x] Create a property named `serviceId` that contains the value of the `id` of the `service` or `null` if `service` is `null`.
- [x] Create a property named `spatialSelectionServiceId` that contains the value of the `id` of the `spatialSelectionService` or `null` if `spatialSelectionService` is `null`.
- [x] Create a property named `spatialSelectionServiceName` that contains the value of the `name` of the `spatialSelectionService` or `null` if `spatialSelectionService` is `null`.
