### ISSUE TITLE
Add cartography id, cartography name, cartography layers (field) and territory id projection to cartography availability

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#59]
CartographyAvailability needs a projection that shows the id, name and layers (field) code of the Cartography and id of the Territory.

**Comment by fjlopez** [comment]
This requires:
- [x] Create a property named `cartographyId` that contains the value of the `id` of the `cartography` or `null` if `cartography` is `null`.
- [x] Create a property named `cartographyName` that contains the value of the `name` of the `cartography` or `null` if `cartography` is `null`.
- [x] Create a property named `cartographyLayers that contains the value of the `layers` of the `cartography` or `null` if `cartography` is `null`.
- [x] Create a property named `territoryId that contains the value of the `id` of the `territory` or `null` if `territory` is `null`.
