### ISSUE TITLE
Add territory id, territory name, grouptask name, and task id projection to task availability

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#61]
TaskAvailability needs a projection that shows the id and the name of the Territory allowed to access to the task. And Grouptask name and task id of the task

**Comment by fjlopez** [comment]
This requires:
- [x] Create a projection for `TaskAvailability ` named `view`.
- [x] Create a property named `territoryId` that contains the value of the `id` of the `territory` or `null` if `territory` is `null`.
- [x] Create a property named `territoryName` that contains the value of the `name` of the `territory` or `null` if `territory` is `null`.
- [x] Create a property named `taskId` that contains the value of the `id` of the `task` or `null` if `task` is `null`.
- [x] Create a property named `taskGroupName` that contains the value of the `name` of the `task.group` or `null` if `task` o `task.group` are `null`.
