### ISSUE TITLE
Save cartographyParameters Error

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#63]
when save a new cartography parameter, I receive this error:
```json
{
  "errors" : [ {
    "entity" : "CartographyParameter",
    "property" : "cartography",
    "invalidValue" : null,
    "message" : "must not be null"
  } ]
}
```
but `cartography` value was `http://localhost:8080/api/cartographies/1228`.

Har file: [localhost3.zip](https://github.com/sitmun/sitmun-backend-core/files/5944274/localhost3.zip)

UPDATE: The request was

```http
POST /api/cartography-parameters
...
{ 
  "value":"prova",
  ...
  "cartography":"http://localhost:8080/api/cartographies/1228"
}

**Comment by fjlopez** [comment]
Bug fixed
