### ISSUE TITLE
Management of permission from the user screen

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#65]
We are developing the proposal that I made yesterday for the management of permissions from the user screen, and I have seen one thing, the USR_CONF table has the UCO_ROLEID field as non-null, and that is not correct, since if we want to add a role for the children of a parent territory what we will do is fill in the UCO_ROLEMID field and the UCO_ROLEID will be null. 
Therefore, just as the UCO_ROLEMID can be null, the UCO_ROLEID must also be null.

**Comment by fjlopez** [comment]
@lucenasj , the data model of JM seems that in `USR_CONF`, given a user and a territory either you can set:

- the role for the parent territory and the role for all the children territories for a given user
- the role for a territory for a given user

A simpler solution and related to your proposal is to update the data model as follows:
-  `UCO_ROLEMID` is replaced by a boolean field `UCO_ROLEM`
- if `UCO_ROLEM` is `false`, `UCO_ROLEID` is the role for the territory for a given user
- if `UCO_ROLEM` is `true`, `UCO_ROLEID` is the role for the direct children of a territory for a given user

In addition, I need to know if `APP_ENTRYM` is related with `UCO_ROLEMID` (or `UCO_ROLEM` if we use the simpler approach). Is the following correct?
- If an application has `APP_ENTRYM` as `true` and it is related with a role in `USR_CONF` that has `UCO_ROLEM` as `true`, then the user has such role enabled for the direct children of the territory.
- If an application has `APP_ENTRYM` as `false` and it is related with a role in `USR_CONF` that has `UCO_ROLEM` as `true`, then the this configuration is ignored.

In addition, I don't understand the purpose of `APP_ENTRYS`, what does it imply in terms of user configuration if this value is true or false.?

**Comment by lucenasj** [comment]
**this is a good solution:**
UCO_ROLEMID is replaced by a boolean field UCO_ROLEM
if UCO_ROLEM is false, UCO_ROLEID is the role for the territory for a given user
if UCO_ROLEM is true, UCO_ROLEID is the role for the direct children of a territory for a given user


**In addition, I need to know if APP_ENTRYM is related with UCO_ROLEMID (or UCO_ROLEM if we use the simpler approach). Is the following correct?**
Yes, APP_ENTRYM is related with UCO_ROLEMID, and what you say is correct

**Comment by fjlopez** [comment]
This change implies:

- [ ] replace UCO_ROLEMID by UCO_ROLEM 
- [ ] new property `appliesToChildrenTerritories`
- [ ] drop of property `roleChildren`
- [ ] drop of property `roleChildrenId` in view
- [ ] drop of property `roleChildrenName` in view
