### ISSUE TITLE
Save treenode error

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#68]
when save a new treenode, I receive this error:

{
  "errors" : [ {
    "entity" : "TreeNode",
    "property" : "tree",
    "invalidValue" : null,
    "message" : "must not be null"
  } ]
}
but tree value was "http://localhost:8080/api/trees/1"

Har file: 
[treenode.zip](https://github.com/sitmun/sitmun-backend-core/files/5958405/treenode.zip)

**Comment by fjlopez** [comment]
This seems to be a problem in the front. I just tested the following request in a test:

```http
POST /api/tree-nodes

{
  "name": "test",
  "tree": "http://localhost/api/trees/1"
}
```

And returns `201 Created`.

**Comment by lucenasj** [comment]
[treenode (2).zip](https://github.com/sitmun/sitmun-backend-core/files/5963519/treenode.2.zip)

can you test this har?

**Comment by fjlopez** [comment]
Tested. The problem is that you are posting in the property `parent` the object that represents the parent node instead of the link to the parent node, i.e.:

```json
{
    "name": "prova",
    "tooltip": null,
    "active": null,
    "cartography": null,
    "tree": "http://localhost:8080/api/trees/2",
    "_links": null,
    "parent": {
        "name": "Ortofotos i imatges (DIBA - ICGC)",
        "parent": null,
        "id": 416
...
```
The fix is on your side. As the parent has the `id` 416 you should simply POST 

```http
POST /api/tree-nodes

{
    "name": "prova",
    "tooltip": null,
    "active": null,
    "cartography": null,
    "tree": "http://localhost:8080/api/trees/2",
    "parent": "http://localhost:8080/api/treee-nodes/416"
}
```
