### ISSUE TITLE
Save user error

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#69]
When save a new user, I don't recieve the object saved but it have been saved and the code response is good, if I put / at final of url, I recieve the object.

**Comment by fjlopez** [comment]
I found duplicate code in the backend created by GeoSlab related to this issue. I need to know which is used in the front to remove extra code. @lucenasj confirm which of these are in use or are planned to be used in the front.

- [ ] `POST /api/users` : fine, creates a new user
- [ ] `GET, PUT, DELETE /api/users/{id}` : fine, manages an existing user
- [ ] `POST /api/account` : update logged user (uses the token JWT to identify the id)
- [ ] `GET /api/account` : get details of the logged user (uses the token JWT to identify the id)
- [ ] `POST /api/account/change-password`: updates its password (uses the token JWT to identify the id) 
- [ ] `POST /users`  :  create a user 
- [ ] `PUT /users/{id}` : modifies a user, delete 
- [ ] `POST /users/{id}/change-password`: updates its password 

However, I think that simpler and consistent with the API is the following configuration. @lucenasj mark which 

- [ ] `POST /api/users` : fine, creates a new user
- [ ] `GET, PUT, DELETE /api/users/{id}` : fine, manages an existing user
- [ ] `GET /api/account` : get details of the logged user (uses the token JWT to identify the id)
- [ ] `PUT /api/account` : update the logged user (uses the token JWT to identify the id)

**Comment by fjlopez** [comment]
`GET` will do not return the field `password` for safety reasons.
`PUT` and `POST` can use the field `password`

In `POST`,  the semantics of `password` is as follow:
- the field is not present or its value is `null` or and empty string: set the password to `null`
- the field is present but its value is not `null` or  empty string: the field contains the new password value

In `PUT`,  the semantics of `password` is as follow:
- the field is not present or its value is `null`: preserve the previous stored password
- the field is present but its value is an empty string: set the password to `null`
- the field is present but its value is not `null` or  empty string: the field contains the new password value
