### ISSUE TITLE
Modify type of cartography group error

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-backend-core#70]
If cartography group type is modified, the request don't work, we change url to request to the type (Background, SituationMap, LocationMap), but not work.

**Comment by fjlopez** [comment]
Can you provide a har file?

**Comment by fjlopez** [comment]
@lucenasj send me a har file to better understand this task. I have several doubts:

- Is `CartographyPermissions.type` your "cartography group type"?
- Do you have tried to changed from `CartographyPermission` (type = "C") to `Background Map` (type = "F") or `Situation Map` (type "M")?
- Do you have tried to change  the type of a `Background Map` (type = "F") or `Situation Map` (type "M") when they are related to a `Background` or an `Application`? This is forbidden in the model as the association must be erased first.
- What is a Location Map from the point of view of user in the application administration? Is it an alias of `Situation Map` for an `Application`?

**Comment by lucenasj** [comment]
**Is CartographyPermissions.type your "cartography group type"?**
Yes
**Do you have tried to changed from CartographyPermission (type = "C") to Background Map (type = "F") or Situation Map (type "M")?**
Yes, and we change de link self, because is another subclass.
**Do you have tried to change the type of a Background Map (type = "F") or Situation Map (type "M") when they are related to a Background or an Application? This is forbidden in the model as the association must be erased first.**
I don't understand this.
**What is a Location Map from the point of view of user in the application administration? Is it an alias of Situation Map for an Application?**
I don't understand this, in application detail we can change de Cartrography permissions by a select.

**Comment by fjlopez** [comment]
I need to know how you have tried to change the type to reproduce the issue (e.g. the har file).

If an application has a situation map, it means that `APP_GGIID` must have the id of a `CartographyPermission` of type "M" (i.e. `SituationMap`). In such case you cannot change the type of such `CartographyPermission` to a different one (e.g. "C" or "F") because you will violate the contract. You can only change the type of a `CartographyPermission` of type "M" if no application uses it. 

With "Location Map", I refer to this that you have said "_we change url to request to the type (Background, SituationMap, **LocationMap**)_".

**Comment by fjlopez** [comment]
@lucenasj Fixed. Back to the original behaviour so we can change it without problem. It also implies implies that:

- `/api/background-maps` should be replaced by `/api/cartography-groups?type=F` 
- `/api/background-maps/{0}` should be replaced by `/api/cartography-groups/{0}` 
- `/api/situation-maps` should be replaced by `/api/cartography-groups?type=M` 
- `/api/situation-maps/{0}` should be replaced by `/api/cartography-groups/{0}` 

The issue should be kept open as this must be also fixed:
- [ ] the change to the type must be forbidden when the `CartographyPermission` is used as a background map or as a situation map. 
- [ ] only `CartographyPermission`s of type background maps (`F`) can be used as background map in `Background`.
- [ ] only `CartographyPermission`s of type situation maps (`M`) can be used as situation map in `Application`.
