### ISSUE TITLE
List of tasks and layers available for an application

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-backend-core#78]
Add in the APPLICATION form new tables to let the administrator know all the tasks and layers that one application has acces to.

**Comment by fjlopez** [comment]
@IDEmenorca once this feature is available in the backend I think that @lucenasj can add it easily to the admin as the idea is that these lists are read only.

**Comment by fjlopez** [comment]
Added two new query endpoints:

- `/api/tasks/search/available?applicationId=:id` where `:id` is the identifier of an application return the tasks that are available to such application (application - role - task). 
- `/api/cartographies/search/available?applicationId=:id` where `:id` is the identifier of an application return the cartographies that are available to such application (application - role - cartographyPermission - cartography).

**Comment by fjlopez** [comment]
@IDEmenorca @lucenasj  could you confirm me this is solution is solves the issue?
