### ISSUE TITLE
New attribute on Background

### ISSUE THREAD

**Issue by gon-nexus** [sitmun/sitmun-backend-core#80]
We need a new attribute on Background (STM_BACKGRD):  img(icon)

**Comment by fjlopez** [comment]
@gon-nexus, please confirm if `image` or ìcon` is a  URL

**Comment by gon-nexus** [comment]
Yes, image is an URL

**Comment by gon-nexus** [comment]
The attribute "image" not appears if projection=view is enabled:

http://localhost:8080/api/backgrounds?projection=view return this response:
![image](https://user-images.githubusercontent.com/73172087/111337894-c12ac280-8676-11eb-907b-8f3a3ea0f0f4.png)

And http://localhost:8080/api/backgrounds returns this response:

![image](https://user-images.githubusercontent.com/73172087/111338001-dbfd3700-8676-11eb-894f-25ea13818927.png)

**Comment by fjlopez** [comment]
@gon-nexus fixed

**Comment by gon-nexus** [comment]
All is correct now, thanks!
