### ISSUE TITLE
Update fields with default values

### ISSUE THREAD

**Issue by fjlopez** [sitmun/sitmun-backend-core#89]
From the meet:
- [x] @lucenasj or @gon-nexus will provide the fields with default values, so we can add them to the backend.

_Originally posted by @fjlopez in https://github.com/sitmun/sitmun-backend-core/issues/82#issuecomment-803400424_

**Comment by gon-nexus** [comment]
These are the fields with default values:
(Entity -> Attribute)
STM_APP -> createdDate
STM_TERRITORY -> createdDate
STM_USER -> createdDate
STM_SERVICE -> createdDate
STM_GEOINFO -> createdDate

**Comment by fjlopez** [comment]
@gon-nexus STM2 has more default values that are not set by the SITMUN2 UI.  For example, "Descàrrega" and "Document" use the same table in the backend for storing data. The field type is managed by the UI en "Document" (values "A" *Aplicació* and "C" *Capa*) but no in "Descàrrega", however, "Descàrrega" data has a value "U" that it is not set by the UI.

The best way to detect it is to review for each entity each form to detect which fields are not editable by the user in the UI or for which fields do you provide a default value.

**Comment by fjlopez** [comment]
> @gon-nexus STM2 has more default values that are not set by the SITMUN2 UI. For example, "Descàrrega" and "Document" use the same table in the backend for storing data. The field type is managed by the UI en "Document" (values "A" _Aplicació_ and "C" _Capa_) but no in "Descàrrega", however, "Descàrrega" data has a value "U" that it is not set by the UI.

This scenario will not occur in SITMUN3 as the STM_DOWNLOAD table is deprecated.

**Comment by fjlopez** [comment]
@gon-nexus In `POST`, `createdDate` now is set by the server:
> STM_APP -> createdDate
> STM_TERRITORY -> createdDate
> STM_USER -> createdDate
> STM_SERVICE -> createdDate
> STM_GEOINFO -> createdDate

If required, `createdDate` can be edited with `PUT`.

**Comment by fjlopez** [comment]
@fjlopez Add `Task.createdDate`

**Comment by gon-nexus** [comment]
Works as expected! Thanks!
