### ISSUE TITLE
Save task

### ISSUE THREAD

**Issue by gon-nexus** [sitmun/sitmun-backend-core#97]
With the new "tasks system" exists the possibility to save the relations tables like an attribute?
Example: If the task has de table of roles, save the content of that table in task.roles (as URI list)

**Comment by fjlopez** [comment]
Yes, but the solution should take into account that it requires to provide a general solution to relate a task with other tasks with a qualifier. 

I have identified at least 3 cases in STM2: 

A table (a task) "Relacionada amb" another table (a tasks). IMHO, in STM2 the a table can be related with at most other table. Let's qualify this relation as "related".

<img src="https://user-images.githubusercontent.com/3294927/116212499-2cbb8180-a745-11eb-94b0-47e7340733d1.png" width="500">

A table (a task) with a "vista de cerca" (also a task). Let's qualify this relation as "search".

<img src="https://user-images.githubusercontent.com/3294927/116213550-2e397980-a746-11eb-896c-6dc38a77654d.png"  width="500">

A "Mes informació" (a task) related to an "informe" (also a task). Let's qualify this relation as "report".

<img src="https://user-images.githubusercontent.com/3294927/116212929-a05d8e80-a745-11eb-821e-cdca0c08c9a7.png" width="500">

Can you identify any additional use case?

I think that this can be implemented with a table with the tuple (id, task, qualifier, target task) that is accessible with an attribute in Task similar to task.roles as you suggest. 

Share your thoughs.

**Comment by fjlopez** [comment]
@gon-nexus any thoughts on this?

**Comment by fjlopez** [comment]
@lucenasj @gon-nexus implemented the relation between tables as part of the efforts for implementing #94 

- `Tasks` have an additional association property named `relations`. This property replaces previous association properties `parent` and `children` as includes them as a special case
- Elements of this relations are `TaskRelations` which can be found at `/api/task-related`. `TaskRelations` have four properties:
   - `id` as they have identity (i.e. `/api/task-related/{id}` returns its representation) 
   - `relationType`, a mandatory string that qualifies the relation
   - `task`, the `Task` that owns the relation.
   - `relatedTask`, the `Task` target of the relation.

`parent` and `children` relations can be implemented, e.g., with a `TaskRelation` with a `relationType` of value `"child"`.
